CREATE PROCEDURE dbo.SP_MOV_INVENTARIO_INSERT
(
    @COD_CIA varchar(5),
    @COMPANIA_VENTA_3 varchar(5),
    @ALMACEN_VENTA varchar(10),
    @TIPO_MOVIMIENTO varchar(2),
    @TIPO_DOCUMENTO varchar(2),
    @NRO_DOCUMENTO varchar(50),
    @COD_ITEM_2 varchar(50),
    @CANTIDAD int,
    @FECHA_TRANSACCION DATE
)
AS
BEGIN
    INSERT INTO MOV_INVENTARIO
    VALUES (
        @COD_CIA, @COMPANIA_VENTA_3, @ALMACEN_VENTA,
        @TIPO_MOVIMIENTO, @TIPO_DOCUMENTO,
        @NRO_DOCUMENTO, @COD_ITEM_2,
        NULL, NULL, @CANTIDAD,
        NULL, NULL, NULL, NULL, NULL,
        @FECHA_TRANSACCION
    )
END
