CREATE PROCEDURE dbo.SP_MOV_INVENTARIO_UPDATE
(
    @COD_CIA varchar(5),
    @COMPANIA_VENTA_3 varchar(5),
    @ALMACEN_VENTA varchar(10),
    @TIPO_MOVIMIENTO varchar(2),
    @TIPO_DOCUMENTO varchar(2),
    @NRO_DOCUMENTO varchar(50),
    @COD_ITEM_2 varchar(50),
    @CANTIDAD int
)
AS
BEGIN
    UPDATE MOV_INVENTARIO
    SET CANTIDAD = @CANTIDAD
    WHERE COD_CIA = @COD_CIA
      AND COMPANIA_VENTA_3 = @COMPANIA_VENTA_3
      AND ALMACEN_VENTA = @ALMACEN_VENTA
      AND TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO
      AND TIPO_DOCUMENTO = @TIPO_DOCUMENTO
      AND NRO_DOCUMENTO = @NRO_DOCUMENTO
      AND COD_ITEM_2 = @COD_ITEM_2
END
